"""
NetWatch AI — WebSocket Endpoints
Real-time traffic and alert streaming via WebSocket.
"""

import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Set

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

logger = logging.getLogger("netwatch.websocket")

router = APIRouter()

# Connection registries
live_traffic_clients: Set[WebSocket] = set()
alert_clients: Set[WebSocket] = set()


@router.websocket("/ws/live")
async def ws_live_traffic(websocket: WebSocket):
    """
    Real-time traffic flow stream.
    Clients receive enriched flow data as it arrives from NATS.
    """
    await websocket.accept()
    live_traffic_clients.add(websocket)
    logger.info(f"WebSocket /ws/live connected — {len(live_traffic_clients)} clients")

    try:
        while True:
            # Send heartbeat every 30 seconds to keep connection alive
            # In Phase 3, this will be replaced by NATS subscription forwarding
            await asyncio.sleep(30)
            await websocket.send_json({
                "type": "heartbeat",
                "timestamp": int(datetime.now(timezone.utc).timestamp()),
                "message": "WebSocket alive — awaiting traffic data from capture agent",
            })
    except WebSocketDisconnect:
        live_traffic_clients.discard(websocket)
        logger.info(f"WebSocket /ws/live disconnected — {len(live_traffic_clients)} clients")
    except Exception as e:
        live_traffic_clients.discard(websocket)
        logger.error(f"WebSocket /ws/live error: {e}")


@router.websocket("/ws/alerts")
async def ws_alerts(websocket: WebSocket):
    """
    Real-time alert stream.
    Clients receive new alerts as they are generated by ML engine.
    """
    await websocket.accept()
    alert_clients.add(websocket)
    logger.info(f"WebSocket /ws/alerts connected — {len(alert_clients)} clients")

    try:
        while True:
            # Send heartbeat every 30 seconds
            await asyncio.sleep(30)
            await websocket.send_json({
                "type": "heartbeat",
                "timestamp": int(datetime.now(timezone.utc).timestamp()),
                "message": "Alert WebSocket alive — awaiting alert data",
            })
    except WebSocketDisconnect:
        alert_clients.discard(websocket)
        logger.info(f"WebSocket /ws/alerts disconnected — {len(alert_clients)} clients")
    except Exception as e:
        alert_clients.discard(websocket)
        logger.error(f"WebSocket /ws/alerts error: {e}")


async def broadcast_traffic(data: dict):
    """Broadcast traffic data to all connected live traffic clients."""
    if not live_traffic_clients:
        return
    message = json.dumps(data)
    disconnected = set()
    for ws in live_traffic_clients:
        try:
            await ws.send_text(message)
        except Exception:
            disconnected.add(ws)
    if disconnected:
        live_traffic_clients.difference_update(disconnected)


async def broadcast_alert(data: dict):
    """Broadcast alert data to all connected alert clients."""
    if not alert_clients:
        return
    message = json.dumps(data)
    disconnected = set()
    for ws in alert_clients:
        try:
            await ws.send_text(message)
        except Exception:
            disconnected.add(ws)
    if disconnected:
        alert_clients.difference_update(disconnected)
